ROS Node Implementation for timestamping
ethz-asl/time_stamper pull request #1
Opened 2022-02-23 13:19 UTC by 4c3y

## Features
- Implemented a C++ [sysfs](https://en.wikipedia.org/wiki/Sysfs) interface to access Raspberry Pi's Hardware PWM timers.
- Implemented TimestampManager which polls for new timestamps generated by the kernelmodule.
- Implemented ROS Node with timestamp publisher.
- Added unittests with sysfs mock
- Added docs in header files

2022-02-23 19:18 UTC, michaelpantic requested changes
Nice and readable code, well done!

Of course I always find things to complain about, see comments.
Let me know when you addressed them, then I have a second look!

2022-02-23 19:18 UTC, michaelpantic commented on time_stamper_ros/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.0.2)
We normally use catkin simple - please switch to it

2022-02-23 19:18 UTC, michaelpantic commented on time_stamper_ros/CMakeLists.txt
> +#find_library(WIRINGPI_LIBRARIES NAMES wiringPi)
Remove unused stuff

2022-02-23 19:18 UTC, michaelpantic commented on time_stamper_ros/include/IPwmSubsystem.h
> +class IPwmSubsystem {
Interfaces are a good place to document interfaces :-)

Please add comments and documentation for the interfacce and the individual functions.
Naming of the functions is pretty good, but not always self-evident. E.g. from only code its not clear what the difference between SetDutyCycle and SetDutyCycleRaw is, or what the write function is for

2022-02-23 19:18 UTC, michaelpantic commented on time_stamper_ros/include/IPwmSubsystem.h
> +  virtual bool SetFrequency(int hz) = 0;
use uint32 or 16 (what are the maximums?)

btw, is frequency always integer?

2022-02-23 19:18 UTC, michaelpantic commented on time_stamper_ros/include/IPwmSubsystem.h
> +class IPwmSubsystem {
ah, I just saw all the (good) comments in the implemented class. Maybe its better to move them to the interface?

2022-02-23 19:18 UTC, michaelpantic commented on time_stamper_ros/msg/Timestamp.msg
> +float64 timestamp
Ros useually uses ros::Time for timestamps. Any reason not to add it too?

2022-02-23 19:18 UTC, michaelpantic commented on time_stamper_ros/src/Node.cpp
> +    usleep(1e3 * 10);
needed for lowlevel things? Add comment

2022-02-23 19:18 UTC, michaelpantic commented on time_stamper_ros/src/SysfsPwm.cpp
> +      && Write("/pwm0/period", "10000000")
magic strings, should be class variables with comments

2022-02-23 19:18 UTC, michaelpantic commented on time_stamper_ros/src/SysfsPwm.cpp
> +      && Write("/pwm0/period", "10000000")
For putting together the file paths, you could use std::filesystem::path for the individual parts, eg. pwm0, period etc as static class variables, and then concatenate them together.

https://en.cppreference.com/w/cpp/filesystem/path

2022-02-23 19:18 UTC, michaelpantic commented on time_stamper_ros/src/SysfsPwm.cpp
> +  if (a == 1) {
you can just return a==1 as last statement here

2022-02-23 19:18 UTC, michaelpantic commented on time_stamper_ros/src/SysfsPwm.cpp
> +  std::string value_str = std::to_string(5000000);
static class member for magic strings

2022-02-23 19:18 UTC, michaelpantic commented on time_stamper_ros/src/SysfsPwm.cpp
> +  int freq = (int) 1e9 / hz;
hmm can this ever go wrong? Test input range to make sure it doesnt

2022-02-23 19:18 UTC, michaelpantic commented on time_stamper_ros/src/SysfsPwm.cpp
> +  int freq = (int) 1e9 / hz;
(think about very large, negative or 0 hz

2022-02-23 19:18 UTC, michaelpantic commented on time_stamper_ros/src/SysfsPwm.cpp
> +  DIR *pDir = opendir(path);
could use https://www.gnu.org/software/libc/manual/html_node/Testing-File-Type.html

2022-02-23 19:18 UTC, michaelpantic commented on time_stamper_ros/test/test_mock_pwm_subsystem.cc
> +  //TODO define valid range
do todos :-)

2022-02-23 19:18 UTC, michaelpantic commented on time_stamper_ros/test/test_mock_pwm_subsystem.cc
> +  //TODO implement
same

2022-02-28 11:06 UTC, 4c3y commented
Addressed all requested changes and added additional documentation. As we discussed last week I extracted a filesystem interface from the pwm subsystem interface to improve test coverage.

2022-03-01 12:00 UTC, michaelpantic approved these changes
Well done! Code looks good, the new unit tests are also good.

Just see my comment about breaking them up - its not wrong to have only one test statement per unit tests, so the CI results are easier to track. Once the unit tests are broken up, just merge!

2022-03-01 12:00 UTC, michaelpantic commented on time_stamper_ros/test/Tests/test_mock_filesystem.cc
> +  bool setFrequencyResult = sysfs_pwm.SetFrequency(IPwmSubsystem::PWM_MAXSPEED_HZ + 1);
Unit tests should be as minimal as possible, so better to break up into smaller ones.

Otherwise good tests!

2022-03-01 12:02 UTC, michaelpantic commented on time_stamper_ros/test/Tests/test_mock_filesystem.cc
> +  bool setFrequencyResult = sysfs_pwm.SetFrequency(IPwmSubsystem::PWM_MAXSPEED_HZ + 1);
see e.g https://osherove.com/blog/2005/4/3/a-unit-test-should-test-only-one-thing.html

2022-03-01 15:33 UTC, merged